// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PulsGrada.Data;

#nullable disable

namespace PulsGrada.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PulsGrada.Models.Dogadaj", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("KategorijaId")
                        .HasColumnType("integer")
                        .HasColumnName("kategorija_id");

                    b.Property<int>("LokalId")
                        .HasColumnType("integer")
                        .HasColumnName("lokal_id");

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("naziv");

                    b.Property<string>("Opis")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("opis");

                    b.Property<int>("OrganizatorId")
                        .HasColumnType("integer")
                        .HasColumnName("organizator_id");

                    b.Property<string>("UrlSlike")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("url_slike");

                    b.Property<DateTime>("VrijemePocetka")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("vrijeme_pocetka");

                    b.HasKey("Id");

                    b.HasIndex("KategorijaId");

                    b.HasIndex("LokalId");

                    b.HasIndex("OrganizatorId");

                    b.ToTable("dogadaji");
                });

            modelBuilder.Entity("PulsGrada.Models.Favorit", b =>
                {
                    b.Property<int>("KorisnikId")
                        .HasColumnType("integer")
                        .HasColumnName("korisnik_id");

                    b.Property<int>("LokalId")
                        .HasColumnType("integer")
                        .HasColumnName("lokal_id");

                    b.HasKey("KorisnikId", "LokalId");

                    b.HasIndex("LokalId");

                    b.ToTable("favoriti");
                });

            modelBuilder.Entity("PulsGrada.Models.Kategorija", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("naziv");

                    b.HasKey("Id");

                    b.ToTable("kategorije");
                });

            modelBuilder.Entity("PulsGrada.Models.Korisnik", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DatumRegistracije")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("datum_registracije");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("Ime")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("ime");

                    b.Property<string>("KorisnickoIme")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("korisnicko_ime");

                    b.Property<string>("Lozinka")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("lozinka");

                    b.Property<string>("Prezime")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("prezime");

                    b.HasKey("Id");

                    b.ToTable("korisnici");
                });

            modelBuilder.Entity("PulsGrada.Models.Kvart", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("naziv");

                    b.HasKey("Id");

                    b.ToTable("kvartovi");
                });

            modelBuilder.Entity("PulsGrada.Models.Lokal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Adresa")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("adresa");

                    b.Property<bool>("ImaBiljar")
                        .HasColumnType("boolean")
                        .HasColumnName("ima_biljar");

                    b.Property<bool>("ImaPikado")
                        .HasColumnType("boolean")
                        .HasColumnName("ima_pikado");

                    b.Property<bool>("ImaPusenje")
                        .HasColumnType("boolean")
                        .HasColumnName("ima_pusenje");

                    b.Property<bool>("IsPremium")
                        .HasColumnType("boolean")
                        .HasColumnName("is_premium");

                    b.Property<int>("KategorijaId")
                        .HasColumnType("integer")
                        .HasColumnName("kategorija_id");

                    b.Property<double>("KordinataX")
                        .HasColumnType("double precision")
                        .HasColumnName("lat");

                    b.Property<double>("KordinataY")
                        .HasColumnType("double precision")
                        .HasColumnName("lng");

                    b.Property<int>("KvartId")
                        .HasColumnType("integer");

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("naziv");

                    b.Property<string>("Opis")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("opis");

                    b.Property<string>("RadnoVrijeme")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("radno_vrijeme");

                    b.Property<string>("UrlCjenik")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("url_cjenik");

                    b.Property<string>("UrlSlike")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("url_slike");

                    b.HasKey("Id");

                    b.HasIndex("KategorijaId");

                    b.HasIndex("KvartId");

                    b.ToTable("lokali");
                });

            modelBuilder.Entity("PulsGrada.Models.Organizator", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("KontaktEmail")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Kontakt_email");

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("naziv");

                    b.Property<string>("Opis")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("opis");

                    b.HasKey("Id");

                    b.ToTable("organizatori");
                });

            modelBuilder.Entity("PulsGrada.Models.Recenzija", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DatumObjave")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("datum_objave");

                    b.Property<string>("Komentar")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("komentar");

                    b.Property<int>("KorisnikId")
                        .HasColumnType("integer")
                        .HasColumnName("korisnik_id");

                    b.Property<int>("LokalId")
                        .HasColumnType("integer")
                        .HasColumnName("lokal_id");

                    b.Property<int>("Ocjena")
                        .HasColumnType("integer")
                        .HasColumnName("ocjena");

                    b.HasKey("Id");

                    b.HasIndex("KorisnikId");

                    b.HasIndex("LokalId");

                    b.ToTable("recenzije");
                });

            modelBuilder.Entity("PulsGrada.Models.Dogadaj", b =>
                {
                    b.HasOne("PulsGrada.Models.Kategorija", "Kategorija")
                        .WithMany()
                        .HasForeignKey("KategorijaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PulsGrada.Models.Lokal", "Lokal")
                        .WithMany()
                        .HasForeignKey("LokalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PulsGrada.Models.Organizator", "Organizator")
                        .WithMany()
                        .HasForeignKey("OrganizatorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Kategorija");

                    b.Navigation("Lokal");

                    b.Navigation("Organizator");
                });

            modelBuilder.Entity("PulsGrada.Models.Favorit", b =>
                {
                    b.HasOne("PulsGrada.Models.Lokal", "Lokal")
                        .WithMany()
                        .HasForeignKey("LokalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lokal");
                });

            modelBuilder.Entity("PulsGrada.Models.Lokal", b =>
                {
                    b.HasOne("PulsGrada.Models.Kategorija", "Kategorija")
                        .WithMany()
                        .HasForeignKey("KategorijaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PulsGrada.Models.Kvart", "Kvart")
                        .WithMany()
                        .HasForeignKey("KvartId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Kategorija");

                    b.Navigation("Kvart");
                });

            modelBuilder.Entity("PulsGrada.Models.Recenzija", b =>
                {
                    b.HasOne("PulsGrada.Models.Korisnik", "Korisnik")
                        .WithMany()
                        .HasForeignKey("KorisnikId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PulsGrada.Models.Lokal", "Lokal")
                        .WithMany("Recenzije")
                        .HasForeignKey("LokalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Korisnik");

                    b.Navigation("Lokal");
                });

            modelBuilder.Entity("PulsGrada.Models.Lokal", b =>
                {
                    b.Navigation("Recenzije");
                });
#pragma warning restore 612, 618
        }
    }
}
